import type { Metadata } from 'next'
import { Navbar } from '@/components/layout/navbar'
import { MinimalFooter } from '@/components/ui/minimal-footer'

export const metadata: Metadata = {
  title: 'Terms of Service — Intervise',
  description: 'The terms and conditions for using Intervise.',
  alternates: { canonical: 'https://intervise.in/terms' },
}

const CARD = {
  backgroundColor: 'rgba(8,13,26,0.75)',
  backdropFilter: 'blur(16px)',
  WebkitBackdropFilter: 'blur(16px)',
  border: '1px solid rgba(249,193,37,0.14)',
  borderRadius: '1rem',
} as const

const SECTIONS = [
  {
    title: '1. Acceptance of terms',
    body: 'By creating an account or using Intervise ("the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service. These terms apply to all users, including free and paid plan subscribers.',
  },
  {
    title: '2. Description of service',
    body: 'Intervise is an AI-powered interview coaching platform. It allows you to practise answering interview questions, receive automated feedback on your speaking pace, filler words, and answer structure, and track your progress over time. The Service is provided for personal, non-commercial use only.',
  },
  {
    title: '3. Account eligibility',
    body: 'You must be at least 16 years old to create an account. By using the Service, you confirm that the information you provide is accurate and that you will keep it up to date. You are responsible for maintaining the security of your account credentials. You may not share your account with others.',
  },
  {
    title: '4. Subscriptions and payments',
    items: [
      'Intervise offers a free tier and paid subscription plans (Student and Pro). Paid plans are billed monthly or quarterly via Razorpay. Prices are shown in Indian Rupees (INR) and are inclusive of applicable taxes.',
      'Subscriptions auto-renew at the end of each billing period unless cancelled. You may cancel at any time from your profile settings page. Cancellation takes effect at the end of the current billing period — you retain full access until then.',
      'We do not issue refunds for partial billing periods. If you believe you were charged in error, contact us at support@intervise.in within 7 days of the charge.',
      'We reserve the right to change pricing with at least 14 days notice. Continued use after a price change takes effect constitutes acceptance of the new price.',
    ],
  },
  {
    title: '5. Session quotas and tier limits',
    body: 'Your plan determines the number of practice sessions available each calendar month (Free: 2, Student: 12, Pro: 30) and the question difficulty levels you may access. Unused sessions do not roll over. Quota limits are enforced server-side and cannot be bypassed.',
  },
  {
    title: '6. Acceptable use',
    items: [
      'Do not attempt to circumvent session quotas, tier restrictions, or payment verification.',
      'Do not use automated tools, bots, or scripts to interact with the Service.',
      'Do not share account credentials with others or create accounts on behalf of others.',
      'Do not reverse-engineer, scrape, or copy the Service, its question bank, or its AI feedback outputs.',
      'Do not upload audio containing content that is unlawful, threatening, abusive, or defamatory.',
      'Do not use the Service for any commercial purpose without our written consent.',
    ],
    footer: 'Violation of these rules may result in immediate account suspension without refund.',
  },
  {
    title: '7. Intellectual property',
    body: 'All content, question banks, software, and designs that make up Intervise are owned by or licensed to us. Your practice transcripts and session data belong to you. By using the Service, you grant us a limited, non-exclusive licence to process your data solely to provide and improve the Service.',
  },
  {
    title: '8. AI-generated content',
    body: 'Feedback generated by Intervise is produced by large language models (OpenAI, Google Gemini) and is automated. It may not be accurate in every case and should be used as one input among many in your interview preparation — not as professional career or legal advice. We are not liable for decisions made based on AI feedback.',
  },
  {
    title: '9. Disclaimers',
    body: 'The Service is provided "as is" without warranties of any kind, express or implied. We do not guarantee that using Intervise will result in job offers, interview success, or any specific outcome. We do not guarantee uninterrupted or error-free operation of the Service.',
  },
  {
    title: '10. Limitation of liability',
    body: 'To the fullest extent permitted by applicable law, Intervise and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of the Service. Our total liability to you for any claim shall not exceed the amount you paid us in the 3 months prior to the claim.',
  },
  {
    title: '11. Termination',
    body: 'We reserve the right to suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time from your profile settings. On termination, your access to the Service ceases immediately and your data will be deleted in accordance with our Privacy Policy.',
  },
  {
    title: '12. Changes to these terms',
    body: 'We may update these Terms from time to time. If we make material changes, we will notify you via the email address on your account at least 14 days before the changes take effect. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.',
  },
  {
    title: '13. Governing law',
    body: 'These Terms are governed by the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the competent courts in India.',
  },
  {
    title: '14. Contact',
    body: null,
    contact: true,
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen text-white">
      <Navbar />
      <main className="mx-auto max-w-3xl px-6 py-20 sm:px-8">

        <div className="mb-12">
          <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-[#F9C125]/70">Legal</p>
          <h1 className="mb-3 text-4xl font-black tracking-tight text-white">Terms of Service</h1>
          <p className="text-sm text-white/40">Last updated: July 2026</p>
        </div>

        <div className="mb-8 rounded-xl p-6" style={CARD}>
          <p className="text-sm leading-relaxed text-white/65">
            Please read these Terms of Service carefully before using Intervise. By accessing or
            using our platform you agree to be bound by these terms.
          </p>
        </div>

        <div className="space-y-5">
          {SECTIONS.map((s) => (
            <div key={s.title} className="p-6 sm:p-7" style={CARD}>
              <h2 className="mb-3 text-base font-bold text-white">{s.title}</h2>
              {s.body && (
                <p className="text-sm leading-relaxed text-white/65">{s.body}</p>
              )}
              {s.items && (
                <ul className="space-y-2.5">
                  {s.items.map((item, i) => (
                    <li key={i} className="flex gap-3 text-sm leading-relaxed text-white/65">
                      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#F9C125]/50" />
                      {item}
                    </li>
                  ))}
                </ul>
              )}
              {s.footer && (
                <p className="mt-3 text-xs text-white/40 italic">{s.footer}</p>
              )}
              {s.contact && (
                <p className="text-sm leading-relaxed text-white/65">
                  For questions about these Terms, contact us at{' '}
                  <a href="mailto:support@intervise.in" className="text-[#F9C125]/80 underline underline-offset-2 hover:text-[#F9C125] transition-colors">
                    support@intervise.in
                  </a>
                </p>
              )}
            </div>
          ))}
        </div>

      </main>
      <MinimalFooter />
    </div>
  )
}
